contact/urls.py
from django.urls import path

from contact.views import ContactPageView

app_name = 'contact'

urlpatterns = [
    path('', ContactPageView.as_view(), name='contact-page')
]

downloads/urls.py
from django.urls import path

from downloads.views import DownloadCreateView, DownloadDeleteView, DownloadListView, DownloadUpdateView

app_name = 'downloads'

urlpatterns = [
    path('', DownloadListView.as_view(), name='list'),
    path('create/', DownloadCreateView.as_view(), name='create'),
    path('update/', DownloadUpdateView.as_view(), name='update'),
    path('delete/', DownloadDeleteView.as_view(), name='delete'),
]

eliheist/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls', namespace='frontend')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('downloads/', include('downloads.urls', namespace='downloads')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/urls.py
from django.urls import path

from frontend.views import HomePageView

app_name = 'frontend'

urlpatterns = [
    path('', HomePageView.as_view(), name='homepage'),
]

projects/urls.py
from django.urls import path

from projects.views import ProjectDetailView, ProjectListView

app_name = 'projects'

urlpatterns = [
    path('', ProjectListView.as_view(), name='project-list'),
    path('<int:pk>/', ProjectDetailView.as_view(), name='project-detail'),
]

api/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models

# Create your models here.

contact/models.py
from django.db import models

# Create your models here.

downloads/models.py
from django.db import models

# Create your models here.
class Download(models.Model):
    name = models.CharField(max_length=100)
    is_image = models.BooleanField(default=False)
    file = models.FileField(upload_to='downloads/')

    def __str__(self):
        return self.name

frontend/models.py
from django.db import models

from projects.models import Project

# Create your models here.
class HProject(models.Model):
    project = models.OneToOneField(Project, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Hompage Project'
        verbose_name_plural = 'Hompage Projects'

    def __str__(self):
        return self.project.name

projects/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=50)
    thumbnail = models.ImageField(upload_to=f'projects/')
    description = models.CharField(max_length=100)
    details = models.TextField()
    technologies = models.ManyToManyField('Technology', related_name='projects', blank=True)
    is_active = models.BooleanField(default=True)

    github_link = models.URLField(null=True, blank=True)
    live_link = models.URLField(null=True, blank=True)

    registered = models.DateTimeField(auto_now_add=True) 
    modified = models.DateTimeField(auto_now=True) 

    class Meta:
        verbose_name = 'Project'
        verbose_name_plural = 'Projects'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """Return absolute url for Project."""
        return ('')

    # TODO: Define custom methods here

class Technology(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'Technology'
        verbose_name_plural = 'Technologies'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """Return absolute url for Technology."""
        return ('')

    # TODO: Define custom methods here

services/models.py
from django.db import models

# Create your models here.

contact/forms.py
from django import forms
from django.core.mail import send_mail

class ContactForm(forms.Form):
    CHOICES = (
        ('Other','Other'),
        ('Web Applications','Web Applications'),
        ('Software Development','Software Development'),
        ('Graphics Design','Graphics Design'),
        ('Music Production','Music Production'),
    )
    name = forms.CharField(max_length=25, required=True)
    email = forms.EmailField(required=True)
    subject = forms.CharField(max_length=50, required=True)
    cartegory = forms.ChoiceField(choices=CHOICES, required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)
    # TODO attachments = forms.FileField(required=False)
    
    def sendMessage(self):
        message = f'''{self.message}\n\n{self.email}'''
        send_mail(f'{self.subject}: {self.cartegory}', message, 'test.eliheist@gmail.com', ['eliyang256@gmail.com',])

api/views.py
from django.shortcuts import render

# Create your views here.

blog/views.py
from django.shortcuts import render

# Create your views here.

contact/views.py
from django.shortcuts import redirect, render

from django.views import View

from contact.forms import ContactForm

# Create your views here.
class ContactPageView(View):
    def get(self, request):
        context = {
            'form': ContactForm()
        }
        template_name = 'contact/contactpage.html'
        return render(request, template_name, context)
    
    def post(self, request):
        form = ContactForm(request.POST)
        form.sendMessage()
        return redirect('contact:contact-page')

downloads/views.py
from django.shortcuts import render
from django.urls.base import reverse_lazy

from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from downloads.models import Download

# Create your views here.
class DownloadListView(ListView):
    template_name = 'downloads/download-list.html'
    model = Download
    context_object_name = 'downloads'

class DownloadCreateView(CreateView):
    template_name = 'downloads/download-create.html'
    model = Download
    fields = '__all__'
    success_url = 'downloads:list'

class DownloadUpdateView(UpdateView):
    template_name = 'downloads/download-update.html'
    model = Download
    fields = '__all__'
    success_url = 'downloads:list'

class DownloadDeleteView(DeleteView):
    template_name = 'downloads/download-delete.html'
    model = Download
    fields = '__all__'

frontend/views.py
from django.shortcuts import render

from django.views import View

from frontend.models import HProject

# Create your views here.
class HomePageView(View):
    def get(self, request):
        context = {
            'projects': HProject.objects.all(),
        }
        template_name = 'frontend/homepage.html'
        return render(request, template_name, context)

projects/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from projects.models import Project

# Create your views here.

class ProjectListView(ListView):
    model = Project
    context_object_name = 'projects'
    template_name = "projects/project-list.html"


class ProjectDetailView(DetailView):
    model = Project
    context_object_name = 'project'
    template_name = "projects/project-detail.html"

services/views.py
from django.shortcuts import render

# Create your views here.

contact/templates/contact/contactpage.html
{% extends 'base.html' %} {% load static tailwind_filters %}

{% block content %}
<main class="pb-8 overflow-hidden scroll-smooth">
    <div class="relative aspect-[2.5/3] sm:aspect-square md:aspect-1610 lg:aspect-video xl:aspect-[16/8] w-full">
        <figure>
            <img src="{% static 'img/call image.jpg' %}" class="object-cover aspect-[2.5/3] sm:aspect-square md:aspect-1610 object-right lg:aspect-video xl:aspect-[16/8] w-full">
        </figure>
        <div class="absolute top-0 left-0 right-0 bottom-0">
            <div class="container mx-auto h-full grid content-end md:content-center relative">
                <div class="grid my-auto">
                    <div class="list">
                        <ol class="grid gap-3 lg:gap-8 text-xl max-w-lg md:max-w-none mx-auto mb-8">
                            <li>
                                <a href="mailto:elijahtriumph@outlook.com" class="grid grid-flow-row lg:grid-flow-col w-fit lg:content-center lg:gap-4">
                                    <i class="fas fa-envelope-open text-6xl mr-2 rotate-12 mb-[-1rem] lg:mb-0"></i>
                                    <span class="grid content-center">elijahtriumph@outlook.com</span>
                                </a>
                            </li>
                            <li>
                                <a href="tel:+256705063168" class="grid grid-flow-row lg:grid-flow-col w-fit lg:content-center lg:gap-4">
                                    <i class="fas fa-phone text-6xl mr-2 mb-4 lg:mb-0"></i>
                                    <span class="grid content-center">+256 705 063 168</span>
                                </a>
                            </li>
                        </ol>
                    </div>
                </div>
                <a href="#form" class="px-4 py-2 rounded-lg outline-grey-900 outline lg:grid place-content-center text-center w-fit absolute bottom-16 left-1/2 -translate-x-1/2 hidden">
                    <span>Send a message</span>
                    <i class="fas fa-chevron-down"></i>
                </a>
            </div>
        </div>
    </div>
    <div>
        <div id="form" class="container px-2 mx-auto py-16">
            <div class="md:hidden">
                
                <p class="max-w-lg mx-auto text-xl text-white font-medium">
                    Hit me up using the details above
                    <br><br>
                    Or......
                </p>
            </div>
            <p class="max-w-lg mx-auto text-xl text-white font-medium bg-primary-500 px-2 mt-4">
                Lets engage.
            </p>
            <form method="POST" class="contact-form bg-dark mx-auto max-w-lg rounded-lg">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="py-2 px-4 bg-primary-500 rounded-md mt-8">
                    <i class="fas fa-envelope-open-text mr-2"></i>
                    Send Message
                </button>
            </form>
        </div>
    </div>
</main>
{% endblock content %}

downloads/templates/downloads/download-create.html
{% extends 'base.html' %} {% load static tailwind_filters %}

{% block content %}
<section class="py-36">
    <div class="container mx-auto">
        <div class="flex justify-end mb-8 p-2">
            <a href="{% url 'downloads:list' %}" class="inline-block rounded-md outline outline-1 outline-grey-400 px-10 py-2 font-semibold text-red-100 shadow-md duration-75 hover:bg-grey-800"><i class="fas fa-list mr-4"></i>File list</a>
        </div>
        <form method="post" class="max-w-2xl mx-auto grid gap-4" enctype="multipart/form-data">
            <h2 class="font-bold text-2xl text-primary-500 pb-8">Add a file below</h2>
            {% csrf_token %}
            {{ form|crispy }}
            <button
                class="inline-block rounded-md bg-green-500 px-6 py-2 font-semibold text-green-100 shadow-md duration-75 hover:bg-green-400">
                Upload File
            </button>
        </form>
    </div>
</section>
{% endblock %}

downloads/templates/downloads/download-list.html
{% extends 'base.html' %}

{% block content %}
<section>
    <div class="container mx-auto py-36">
        <div class="flex justify-end mb-8 p-2">
            <a href="{% url 'downloads:create' %}" class="inline-block rounded-md outline outline-1 outline-grey-400 px-8 py-2 font-semibold text-red-100 shadow-md duration-75 hover:bg-grey-800"><i class="fas fa-cloud-arrow-up mr-4"></i>Upload a file</a>
        </div>
        <div class="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
            {% for file in downloads %}
            <div class="w-full overflow-hidden rounded-lg bg-grey-900 shadow-md duration-300 hover:scale-105 hover:shadow-xl">
                <p xmlns="http://www.w3.org/2000/svg" class="mt-4 mx-4 text-green-400">
                    {% if file.is_image %}
                        <img src="{{ file.file.url }}" class="w-full h-full object-contain">
                    {% else %}
                        <i class="fas fa-file"></i>
                    {% endif %}
                </p>
                <h3 class="mt-2 text-center text-2xl font-bold text-gray-500">{{ file.name }}</h3>
                <p class="my-4 text-center text-sm text-gray-500"></p>
                <div class="space-x-4 bg-grey-900 py-4 text-center">
                    <button
                        class="inline-block rounded-md outline outline-1 outline-grey-400 px-10 py-2 font-semibold text-red-100 shadow-md duration-75 hover:bg-grey-800">
                        <a href="#">Delete</a>
                    </button>
                    <button
                        class="inline-block rounded-md bg-primary-500 px-6 py-2 font-semibold text-red-100 shadow-md duration-75 hover:bg-primary-400">
                        <a href="{{ file.file.url }}" download>Download</a>
                    </button>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

downloads/templates/downloads/download-update.html
{% extends 'base.html' %} {% load static tailwind_filters %}

{% block content %}
<section class="py-36">
    <div class="container mx-auto">
        <div class="flex justify-end mb-8 p-2">
            <a href="{% url 'downloads:list' %}" class="inline-block rounded-md outline outline-1 outline-grey-400 px-10 py-2 font-semibold text-red-100 shadow-md duration-75 hover:bg-grey-800"><i class="fas fa-list mr-4"></i>File list</a>
        </div>
        <form method="post" class="max-w-2xl mx-auto grid gap-4" enctype="multipart/form-data">
            <h2 class="font-bold text-2xl text-primary-500 pb-8">Update file below</h2>
            {% csrf_token %}
            {{ form|crispy }}
            <button
                class="inline-block rounded-md bg-amber-500 px-6 py-2 font-semibold text-amber-100 shadow-md duration-75 hover:bg-amber-400">
                Update File
            </button>
        </form>
    </div>
</section>
{% endblock %}

frontend/templates/frontend/homepage.html
{% extends 'base.html' %} {% load static %}

{% block content %}
<main>
    <!-- banner -->
    <section id="banner" class="py-12">
        <div class="container mx-auto px-2">
            <div class="grid gap-8 sm:grid-cols-3">
                <div class=" sm:col-span-1">
                    <img src="{% static 'img/profile.webp' %}" alt="me">
                </div>
                <div class="sm:col-span-2 grid content-center">
                    <h2 class="font-semibold text-primary-500">Hi, I'm Elijah</h2>
                    <h3 class="text-5xl font-light">I make great Web Applications</h3>
                    <p class=" font-light text-red-100 text-lg py-4">
                        With expertise in Tailwind CSS, Django, and SvelteKit, I bring creative designs to life and build seamless user experiences that are both visually appealing and highly functional.
                    </p>
                    <a href="{% url 'projects:project-list' %}" class="px-4 py-2 bg-primary-500 rounded-lg w-fit">View my Projects</a>
                </div>
            </div>
        </div>
    </section>

    <!-- service cards -->
    <section id="service-cards" class="py-12">
        <div class="container mx-auto px-2">
            <header class="section-header">
                <h2>What I Do.</h2>
            </header>
            <div class="grid gap-4 md:grid-cols-3">
                <article class="home-card">
                    <h3 class="title">UI Development</h3>
                    <p class="lead">
                        Crafting captivating interfaces that blend creativity and cutting-edge technologies, I transform ideas into visually stunning user experiences that leave a lasting impact.
                    </p>
                    <a href="./"><i class="fas fa-eye"></i> Know More</a>
                </article>
                <article class="home-card highlight">
                    <h3 class="title">Backend Development</h3>
                    <p class="lead">
                        With expertise in Django and SvelteKit, I engineer robust back-end systems that power seamless functionality, ensuring your applications are both visually impressive and technically solid.
                    </p>
                    <a href="./"><i class="fas fa-eye"></i> Know More</a>
                </article>
                <article class="home-card">
                    <h3 class="title">Web Deployment</h3>
                    <p class="lead">
                        From integration to performance optimization, I handle the entire deployment process, ensuring your web applications are securely and efficiently launched for a global audience.
                    </p>
                    <a href="./"><i class="fas fa-eye"></i> Know More</a>
                </article>
            </div>
        </div>
    </section>
    <!-- skills -->
    <section id="skills" class="py-12">
        <div class="container mx-auto px-2">
            <div class="flex flex-wrap justify-center gap-8">
                <img src="{% static 'img/skills/js-logo.png' %}" alt="" class="h-8">
                <img src="{% static 'img/skills/ts-logo.png' %}" alt="" class="h-8">
                <img src="{% static 'img/skills/sass-logo.png' %}" alt="" class="h-8">
                <img src="{% static 'img/skills/tailwind-css.png' %}" alt="" class="h-8">
                <img src="{% static 'img/skills/mysql-logo.png' %}" alt="" class="h-8">
                <img src="{% static 'img/skills/python-logo.png' %}" alt="" class="h-8">
                <img src="{% static 'img/skills/django-logo.png' %}" alt="" class="h-8">
            </div>
        </div>
    </section>
    <!-- featured projects -->
    <section id="featured-projects" class="py-12">
        <div class="container mx-auto px-2">
            <header class="section-header">
                <h2>My Projects.</h2>
            </header>
            <div class="grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
                
                {% for hp in projects %}
                <article class="project-card">
                    <figure class="img-control">
                        <img class="img-fluid" src="{{ hp.project.thumbnail.url }}" alt="{{ hp.project.name }}">
                    </figure>
                    <div class="info">
                        <h3>{{ hp.project.name }}</h3>
                        <a href="{% url 'projects:project-detail' hp.project.pk %}"><i class="fas fa-eye"></i> Know
                            more</a>
                    </div>
                </article>
                {% endfor %}
                    
            </div>
        </div>
    </section>
</main>
{% endblock content %}
    

projects/templates/projects/project-detail.html
{% extends 'base.html' %} {% load static %}

{% block content %}
<main>
    <div class="container px-2 mx-auto py-8">
        <div class="grid md:grid-cols-2 gap-8">
            <figure class="thumbnail aspect-surface overflow-hidden rounded-md grid place-content-center">
                <img src="{{ project.thumbnail.url }}" alt="{{ project.name }}" class="object-contain">
            </figure>
            <div class="pt-4">
                <h2 class="project_title text-2xl font-semibold">{{ project.name }}</h2>
                <p class="project_description font-light">
                    {{ project.description }}
                </p>
                <div class="flex flex-wrap gap-2 mt-2">
                    {% for tech in project.technologies.all %}
                    <span class="p-1 bg-grey-900 group-hover:bg-grey-800 text-xs rounded-md">{{ tech.name }}</span>
                    {% endfor %}
                </div>
                <div class="content mt-4 grid gap-2">
                    
                    {% if project.github_link %}
                    <a href="{{ project.github_link }}" class=""><i class="fab fa-github text-white mr-2"></i> View Source Code.</a>
                    {% endif %}
                    
                    {% if project.live_link %}
                    <a href="{{ project.live_link }}" class=" text-lime-500"><i class="fas fa-circle mr-2"></i> View This Project Live.</a>
                    {% endif %}
                        
                </div>
            </div>
                
        </div>
        <div class="py-8">
            <h3 class="hidden">Description</h3>
            <p class="project_description font-light">
                {{ project.details }}
            </p>
        </div>
    </div>
</main>
{% endblock content %}

projects/templates/projects/project-list.html
{% extends 'base.html' %} {% load static %}

{% block content %}
<main>
    <div class="container px-2 mx-auto py-8">
        <div class="grid md:grid-cols-2 gap-8">
            
            {% for project in projects %}
            <article class="project-card-extended group">
                <div class="grid">
                    <div class="grid">
                        <figure class="thumbnail aspect-surface bg-grey-800 group-hover:bg-grey-700 p-4 rounded-md grid place-content-center">
                            <img src="{{ project.thumbnail.url }}" alt="{{ project.name }}" class="h-full object-contain aspect-1610">
                        </figure>
                    </div>
                    <div class="pt-4">
                        <h2 class="project_title text-2xl font-semibold">{{ project.name }}</h2>
                        <p class="project_description font-light">
                            {{ project.description }}
                        </p>
                        <div class="flex flex-wrap gap-2 mt-2">
                            {% for tech in project.technologies.all %}
                            <span class="p-1 bg-grey-900 group-hover:bg-grey-800 text-xs rounded-md">{{ tech.name }}</span>
                            {% endfor %}
                        </div>
                        <div class="content mt-4">
                            <a href="{% url 'projects:project-detail' project.pk %}" class="text-primary-500 font-semibold uppercase">view <i class="fas fa-arrow-right text-white ml-2"></i></a>
                        </div>
                    </div>
                </div>
            </article>
            {% endfor %}
                
        </div>
    </div>
</main>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- my css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">
    <title>EliHeist | Portfolio</title>
</head>
<body>
    <div class="bg-dark text-white font-poppins  selection:bg-primary-500 selection:text-white scroll-smooth">
        {% include 'components/nav.html' %}
        <div>{% block content %}{% endblock content %}</div>
        {% include 'components/footer.html' %}
    </div>
    {% block scripts %}{% endblock scripts %}
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/components/footer.html
<footer class="main-footer">
    <div class="container mx-auto px-2">
        <p class="text-center py-4 text-red-200 text-sm">
            DarkDot &copy; 2023
        </p>
    </div>
</footer>

templates/components/nav.html
<nav id="main-nav">
    <div class="container mx-auto">
        <div class="flex justify-center sm:justify-between py-1">
            <a class="font-bold text-primary-500 p-1 text-2xl" href="./">eliHeist</a>
            <div id="menu" class="hidden sm:inline fixed sm:relative bottom-0 left-0 right-0">
                <menu class="bg-primary-500 sm:bg-transparent grid place-content-center p-8 sm:p-0">
                    <ul class="flex flex-col sm:flex-row uppercase w-fit mb-12 sm:mb-0">
                        <li class="py-4 px-2 sm:py-2 hover:text-primary-500"><a href="{% url 'frontend:homepage' %}">Home</a></li>
                        <li class="py-4 px-2 sm:py-2 hover:text-primary-500"><a href="{% url 'projects:project-list' %}">Projects</a></li>
                        <!-- <li class="py-4 px-2 sm:py-2 hover:text-primary-500"><a href="./projects.html">Beats</a></li>
                        <li class="py-4 px-2 sm:py-2 hover:text-primary-500"><a href="./projects.html">Posts</a></li> -->
                        <li class="py-4 px-2 sm:py-2 hover:text-primary-500"><a href="{% url 'contact:contact-page' %}">Contact</a></li>
                    </ul>
                </menu>
            </div>
        </div>
    </div>
</nav>

<button title="Menu button" class="hamburger-btn grid grid-flow-col sm:hidden z-50" aria-expanded="false">
    <svg class="hamburger w-10" fill="none" viewbox="-10 -10 120 120">
        <path class="line" d="m 20 40 h 60 a 1 1 0 0 1 0 20 h -60 a 1 1 0 0 1 0 -40 h 30 v 70"></path>
    </svg>
    <div class="text-primary-500 h-full grid content-center pr-2 text-sm">
        <span>Menu</span>
    </div>
</button>